---
name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-shumlib:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build and Test (make)
        run: |
          make -f ./make/vm-x86-gfortran-gcc.mk check

      - name: Build and Test (CMake)
        run: |
          cmake --preset debug-gcc
          cmake --build --preset debug-gcc --parallel
          ctest --test-dir build/debug --output-on-failure -V
